module.exports = {
  BoardModel: require("./board-model"),
  CollegeModel: require("./college-model"),
  EducationModel: require("./education-model"),
  CourseModel: require("./course-model"),
  JobApplicationModel: require("./jobApplication-model"),
  JobApprochModel: require("./jobApproach-model"),
  JobTypeModel: require("./jobType-model"),
  NoticePeriodModel: require("./noticePeriod"),
  RoleModel: require("./role-model"),
  SkillModel: require("./skill-model"),
  SearchAppearanceHistoryModel: require("./searchAppearanceHistory-model"),
  AdmissionModel: require("./sms-student-model"),
  ViewedProfileHistory: require("./viewedProfileHistory-model"),
  SpecializationModel: require("./specialization-model"),
  SpeakingLanguageModel: require("./speakingLanguage"),
  JobOfferModel: require("./jobOffer-model"),
  PlanModel: require("./plan-model"),
  DownloadedResumeHistoryModel: require("./downloadedResumeHistory-model"),
  PaymentHistoryModel: require("./paymentHistory-model"),
};
